### ISSUE TITLE
Blank screen after login

### ISSUE THREAD

**Issue by milklineep** [HarryCLucas/KanboardMobile#1]
I tried compiling your app for Android. But as soon as I log in, the app just shows a white screen with a Kanboard logo. What shold I do to get the app to work ?

**Comment by HarryCLucas** [comment]
I'm unsure as to how you're compiling it, but you could try the Debug binary file?
https://github.com/HarryCLucas/KanboardMobile/blob/master/KanboardMobile/bin/Android/Debug/KanboardMobile_Debug.apk

If you're still having issues, let me know what version of Android you're running and we'll work from there.
