### ISSUE TITLE
Willing to help with iOS

### ISSUE THREAD

**Issue by JohnWebmaster** [HarryCLucas/KanboardMobile#2]
This really isn't an issue, but I don't know how else to contact you. I am not a developer, but am an avid fan of KanBoard. I hate using it on my mobile browser and would love to test your app. The only thing is that I have no idea how to compile it. If you can do that for me so I can install it on my phone, I would be more than happy to put it through its paces.

**Comment by HarryCLucas** [comment]
Thanks for the feedback! Please feel free to reach out via the email on my website anytime :)
